"""Resume-domain models, rendering, persistence, and workflow primitives."""

from .context import build_resume_context
from .editor import (
    PreparationNote,
    ResumeEditor,
    ResumeEditorError,
    ResumeEditorResult,
    VisualReviewUnavailable,
)
from .master import MasterResumeDocument, MasterResumeSource, load_resume_pdf
from .models import (
    ApplicationFormAnswer,
    ApplicationPackage,
    ProjectFact,
    ResumeBlock,
    ResumeContext,
    ResumeDocument,
    ResumeEntry,
    ResumeEntryRow,
    ResumeHeader,
    ResumeJobContext,
    ResumeSection,
    RichText,
    RichTextSpan,
)
from .render import (
    ArtifactFile,
    ResumePage,
    ResumeRenderError,
    ResumeRenderResult,
    document_text,
    render_resume,
    resume_template_sha256,
)
from .workflow import (
    ApplyPackWriter,
    ResumeOperation,
    ResumeWorkflow,
    generate_application_package,
    job_snapshot_from_evidence,
)
from .workspace import (
    ArtifactIntegrityError,
    MasterResume,
    MasterResumeNotFoundError,
    ResumeWorkspace,
    ResumeWorkspaceError,
    ResumeWorkspaceRepository,
    WorkspaceConflictError,
    WorkspaceNotFoundError,
    WorkspaceNotReadyError,
    WorkspaceSubmittedError,
)

__all__ = [
    "ApplicationFormAnswer",
    "ApplicationPackage",
    "ApplyPackWriter",
    "ArtifactFile",
    "ArtifactIntegrityError",
    "MasterResume",
    "MasterResumeDocument",
    "MasterResumeNotFoundError",
    "MasterResumeSource",
    "PreparationNote",
    "ProjectFact",
    "ResumeBlock",
    "ResumeContext",
    "ResumeDocument",
    "ResumeEditor",
    "ResumeEditorError",
    "ResumeEditorResult",
    "ResumeEntry",
    "ResumeEntryRow",
    "ResumeHeader",
    "ResumeJobContext",
    "ResumeOperation",
    "ResumePage",
    "ResumeRenderError",
    "ResumeRenderResult",
    "ResumeSection",
    "ResumeWorkflow",
    "ResumeWorkspace",
    "ResumeWorkspaceError",
    "ResumeWorkspaceRepository",
    "RichText",
    "RichTextSpan",
    "VisualReviewUnavailable",
    "WorkspaceConflictError",
    "WorkspaceNotFoundError",
    "WorkspaceNotReadyError",
    "WorkspaceSubmittedError",
    "build_resume_context",
    "document_text",
    "generate_application_package",
    "job_snapshot_from_evidence",
    "load_resume_pdf",
    "render_resume",
    "resume_template_sha256",
]
