"""Shared primitives and domain agents for job and interview research."""

from .browser_bridge import (
    AuthenticatedBrowserBridgeClient,
    AuthenticatedBrowserBridgeStore,
    BrowserBridgeAuthError,
    BrowserBridgeConflictError,
    BrowserBridgeError,
)
from .revisions import RevisionGuard, RevisionSnapshot, StaleRevisionError
from .runner import (
    AgentDefinition,
    AgentExecutionContext,
    AgentRunner,
    AgentRunResult,
    AgentRunStatus,
    AgentSubjectContext,
    AgentTool,
    AgentToolResult,
)
from .sources import (
    AuthenticatedBrowserClient,
    AuthenticatedBrowserPage,
    EvidenceNotFoundError,
    EvidencePage,
    EvidenceRecord,
    FetchExecutionRecord,
    SearchClue,
    SearchExecutionRecord,
    SearchExecutionResult,
    SearchExecutor,
    SourceEvidenceStore,
    SourceFetchResult,
    SourceReader,
    SourceScope,
    UnsafeSourceURLError,
    canonicalize_http_url,
    init_source_evidence_schema,
    validate_public_source_url,
)

__all__ = [
    "AgentDefinition",
    "AgentExecutionContext",
    "AgentRunResult",
    "AgentRunStatus",
    "AgentRunner",
    "AgentSubjectContext",
    "AgentTool",
    "AgentToolResult",
    "AuthenticatedBrowserBridgeClient",
    "AuthenticatedBrowserBridgeStore",
    "AuthenticatedBrowserClient",
    "AuthenticatedBrowserPage",
    "BrowserBridgeAuthError",
    "BrowserBridgeConflictError",
    "BrowserBridgeError",
    "EvidenceNotFoundError",
    "EvidencePage",
    "EvidenceRecord",
    "FetchExecutionRecord",
    "RevisionGuard",
    "RevisionSnapshot",
    "SearchClue",
    "SearchExecutionRecord",
    "SearchExecutionResult",
    "SearchExecutor",
    "SourceEvidenceStore",
    "SourceFetchResult",
    "SourceReader",
    "SourceScope",
    "StaleRevisionError",
    "UnsafeSourceURLError",
    "canonicalize_http_url",
    "init_source_evidence_schema",
    "validate_public_source_url",
]
